// Port of postflop-solver (https://github.com/b-inary/postflop-solver)
// Copyright (C) 2022 Wataru Inariba. Licensed AGPL-3.0-or-later; see LICENSE.
#pragma once

// Feature macros (PFS_ENABLE_THREADS, PFS_CUSTOM_ALLOC,
// PFS_ENABLE_SERIALIZATION, PFS_ENABLE_ZSTD) are generated by CMake from
// cmake/config.hpp.in so the library and its consumers cannot disagree.
#include <pfs/config.hpp>

#include <cstddef>
#include <cstdint>

#if defined(_MSC_VER)
#define PFS_ALWAYS_INLINE __forceinline
#else
#define PFS_ALWAYS_INLINE inline __attribute__((always_inline))
#endif

namespace pfs::detail {
[[noreturn]] void unreachable(const char* file, int line, const char* what);
}

// Equivalent of Rust's `unreachable!()` in the defaulted trait methods, and of
// `panic!` elsewhere. Reaching either is a programming error, never a runtime
// condition, but it throws rather than aborts so the ported tests can observe it.
#define PFS_UNREACHABLE() ::pfs::detail::unreachable(__FILE__, __LINE__, "unreachable")
#define PFS_PANIC(msg) ::pfs::detail::unreachable(__FILE__, __LINE__, (msg))
