"""Regenerate src/hand_table.cpp from the Rust crate's hand_table.rs.

The table is machine-generated data with no generator in the Rust repo, and
Hand::evaluate() returns the *index* into it -- a stable hand ranking that
everything downstream depends on. So it is transcribed verbatim rather than
recomputed.

Usage (from the repo root):
    python tools/gen_hand_table.py ../postflop-solver-main/src/hand_table.rs
"""
import re
import sys
import os

def main():
    rust_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(__file__), "..", "..", "postflop-solver-main", "src", "hand_table.rs")
    with open(rust_path) as f:
        src = f.read()

    m = re.search(r"HAND_TABLE:\s*\[i32;\s*(\d+)\]\s*=\s*\[(.*?)\];", src, re.S)
    if not m:
        raise SystemExit("could not find HAND_TABLE in " + rust_path)

    n = int(m.group(1))
    vals = [int(x) for x in re.findall(r"-?\d+", m.group(2))]
    if len(vals) != n:
        raise SystemExit("expected %d values, parsed %d" % (n, len(vals)))
    if vals != sorted(vals):
        raise SystemExit("table is not ascending; binary search would break")
    if len(set(vals)) != n:
        raise SystemExit("table has duplicates")

    lines = [
        "// Generated by tools/gen_hand_table.py from",
        "// postflop-solver-main/src/hand_table.rs -- do NOT edit by hand.",
        "//",
        "// The %d distinct packed 7-card hand values, ascending." % n,
        "// Hand::evaluate() returns the INDEX into this table, which is the stable hand",
        "// ranking used by everything downstream (StrengthItem::strength is that index",
        "// plus one). Machine-generated data with no generator in the Rust repo, so it is",
        "// transcribed verbatim.",
        '#include "hand_table.hpp"',
        "",
        "namespace pfs {",
        "",
        "const std::array<int32_t, kHandTableSize> kHandTable = {",
    ]
    for i in range(0, n, 12):
        lines.append("    " + ", ".join(str(v) for v in vals[i:i + 12]) + ",")
    lines += ["};", "", "}  // namespace pfs", ""]

    out_path = os.path.join(os.path.dirname(__file__), "..", "src", "hand_table.cpp")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d values, min=%d max=%d)" % (out_path, n, vals[0], vals[-1]))

if __name__ == "__main__":
    main()
